version: "1.0"
timers:
    break: 5m
    long_break: 15m
    work: 25m
theme: default
timer:
    bell_on_complete: false
logging:
    level: info
    file: ""
plugins:
    enabled: []
    directory: ""
